Update ipd-wrapper

diff --git a/ipd-wrapper b/ipd-wrapper
--- a/ipd-wrapper
+++ b/ipd-wrapper
@@ -2,6 +2,7 @@
 PHOTO_DIR="/photos"
 AUTH_DIR="/auth"
 username="$1"
+username="$2"
 
 if ! mountpoint -q $PHOTO_DIR; then
     echo "Photo target directory missing, please pass it as a Docker volume, e.g.:"
@@ -21,6 +22,12 @@ if [ -z $username ]; then
     exit 1
 fi
 
+if [ -z $password ]; then
+    echo "Please pass an Apple ID passwort to Docker, e.g.:"
+    echo "  docker run -ti -v ~/pics/icloud:$PHOTO_DIR -v ~/icloud-secrets:$AUTH_DIR maxhq/ipd myapple@id password"
+    exit 1
+fi
+
 # Restore stored password if existing
 if [ -f $AUTH_DIR/keyring_pass.cfg ]; then
     mkdir -p /root/.local/share/python_keyring/
@@ -35,12 +42,12 @@ fi
 # Password input
 if [ ! -e /root/.local/share/python_keyring/keyring_pass.cfg ]; then
     echo "iCloud password not found in Python keychain, input required"
-    if [ -z $TERM ]; then
-        echo "ERROR: Please run this container once in interactive mode like:"
-        echo "docker run -ti -v ~/pics/icloud:$PHOTO_DIR -v ~/icloud-secrets:$AUTH_DIR maxhq/icloud-photos-downloader myappleid"
-        exit 1
-    fi
-    /usr/local/bin/icloud --username "$username"
+    #if [ -z $TERM ]; then
+    #    echo "ERROR: Please run this container once in interactive mode like:"
+    #    echo "docker run -ti -v ~/pics/icloud:$PHOTO_DIR -v ~/icloud-secrets:$AUTH_DIR maxhq/icloud-photos-downloader myappleid"
+    #    exit 1
+    #fi
+    /usr/local/bin/icloud --username "$username" --password "$password"
     # Backup stored password
     mountpoint -q $AUTH_DIR && cp /root/.local/share/python_keyring/keyring_pass.cfg $AUTH_DIR/
 fi
